---
- name: password reset
  hosts: all
  become: yes

  tasks:
    - name: set new password
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"


"""
The pipeline input can include both the username and password, with the password being designated as sensitive and masked to prevent visibility by the user.

Presently, I use Azure DevOps to create CI/CD pipelines, though I am aware that Jenkins can accomplish the same tasks. In the event that the opportunity arises, I would be open to refreshing my knowledge of Jenkins and utilizing it for future projects.

"""
