---
- name: password reset
  hosts: all
  become: yes

  tasks:
    - name: set new password
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
"""
user name and password can be given as pipline input and password would be marked sensitive. So it will not be visible to users and masked. 

"""
