---
# tasks file for ntp-service-setup
- name: install ntp
  apt:
    name: ntp
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Copy ntp.conf template 
  template:
    src: ntp.j2
    dest: /etc/ntp.conf 
  notify: Restart-NTP 

- name: Start and Enable NTP service 
  systemd:
    name: ntp
    state: started 

"""
 I did not fully understand the question. To include NTP servers dynamically in ntp.conf for each environment, a list of servers is included in the development inventory, and a loop is created inside a Jinja template. However, using the blockinfile module to include the "Ansible managed" message as a comment may not be the appropriate approach in this case.
"""
